# Generated by Django 4.0.6 on 2022-07-16 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='TypeOfTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.CharField(max_length=20, verbose_name='Вид столика')),
            ],
            options={
                'verbose_name': 'Вид столика',
                'verbose_name_plural': 'Виды столов',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_number', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Номер стола')),
                ('number_of_seats', models.SmallIntegerField(verbose_name='Количество мест')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.typeoftable')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('Reserved', 'Зарезервирован'), ('Free', 'Свободен'), ('Wait', 'Ожидает подтверждения')], default='Free')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservation.table')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.SmallIntegerField(verbose_name='Количество мест')),
                ('price_from', models.FloatField(verbose_name='Цена от')),
                ('price_to', models.FloatField(verbose_name='Цена до')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.client')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.typeoftable')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
