# Generated by Django 4.0.6 on 2022-07-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.TextField(choices=[('Reserved', 'Зарезервирован'), ('Wait', 'Ожидает подтверждения')]),
        ),
    ]
